spring.application.name=SmartCampusBackend

spring.datasource.url=jdbc:mysql://localhost:3306/smart_campus?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=kowshik
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT settings
jwt.secret=b45fcb1d283c4856b3ee309eec8a3d5fba45fcb1d283c4856b3ee309eec8a3d5fba
jwt.expiration=86400000

server.port=8080
